const userTypes = { 
    USER_LOGIN_DETAILS         : "USER_LOGIN_DETAILS",
    USER_LOGIN_DETAILS_SUCCESS : "USER_LOGIN_DETAILS_SUCCESS",
    USER_LOGIN_DETAILS_FAILURE : "USER_LOGIN_DETAILS_FAILURE",
    USER_LOGIN_DETAILS_lOADING : "USER_LOGIN_DETAILS_LOADING"
}

export default userTypes;